<<<<<<< HEAD
# Generated by Django 5.0.2 on 2025-06-25 11:49
=======
# Generated by Django 5.0.2 on 2025-06-25 12:37
>>>>>>> 988aa6676617bb749dd1cc28daecd35e3c012db9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='highlights',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='space_type',
            field=models.CharField(choices=[('entire', 'Entire Place'), ('room', 'Private Room')], default='entire', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('boat', 'Boat'), ('cabin', 'Cabin'), ('caravan', 'Caravan'), ('castle', 'Castle'), ('farm', 'Farm'), ('hotel', 'Hotel'), ('riad', 'Riad'), ('tent', 'Tent'), ('tiny', 'Tiny House'), ('tower', 'Tower'), ('treehouse', 'Treehouse'), ('other', 'Other')], max_length=20),
        ),
    ]
