# Generated by Django 5.0.2 on 2025-06-28 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_payment_status_booking_stripe_session_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='app_booking_propert_ee77cb_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='property',
            new_name='property_obj',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('property_obj', 'check_in', 'check_out', 'status')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property_obj', 'check_in', 'check_out'], name='app_booking_propert_9082e7_idx'),
        ),
    ]
