from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('properties/', views.properties, name='properties'),
    path('property/<int:pk>/', views.property_detail, name='property_detail'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('register/', views.register, name='register'),
    path('property/<int:pk>/book/', views.create_booking, name='create_booking'),
    path('booking/<int:pk>/cancel/', views.cancel_booking, name='cancel_booking'),
    path('booking/success/', views.booking_success, name='booking_success'),
    path('booking/cancel/', views.booking_cancel, name='booking_cancel'),
    path('booking/<int:booking_id>/processing/', views.payment_processing, name='payment_processing'),
    path('api/booking/<int:booking_id>/stripe-session/', views.get_stripe_session_url, name='get_stripe_session_url'),
    path('webhooks/stripe/', views.stripe_webhook, name='stripe_webhook'),
    path('api/property/<int:property_id>/availability/', views.check_availability_api, name='check_availability_api'),
    path('api/property/<int:property_id>/unavailable-dates/', views.get_unavailable_dates_api, name='get_unavailable_dates_api'),
    path('api/booking/<int:booking_id>/status/', views.get_booking_status_api, name='get_booking_status_api'),
    path('property/create/', views.create_listing, name='create_listing'),
    path('property/<int:pk>/edit/', views.edit_listing, name='edit_listing'),
    path('property/<int:pk>/delete/', views.delete_listing, name='delete_listing'),
    path('property/<int:pk>/bookings/', views.property_bookings, name='property_bookings'),
    path('review/<int:pk>/edit/', views.edit_review, name='edit_review'),
    path('review/<int:pk>/delete/', views.delete_review, name='delete_review'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('password/change/', views.change_password, name='change_password'),
    path('become-host/', views.become_host, name='become_host'),
    path('create-listing/', views.create_listing, name='create_listing'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('posts/create/', views.create_post, name='create_post'),
    path('manage/posts/', views.manage_posts, name='manage_posts'),
    path('manage/posts/<int:post_id>/approve/', views.approve_post, name='approve_post'),
    path('manage/posts/<int:post_id>/decline/', views.decline_post, name='decline_post'),
    path('host-application/<int:application_id>/approve/', views.approve_host_application, name='approve_host_application'),
    path('host-application/<int:application_id>/reject/', views.reject_host_application, name='reject_host_application'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('user-admin/edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('user-admin/delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('user-admin/toggle-user-status/<int:user_id>/', views.toggle_user_status, name='toggle_user_status'),
    path('user-admin/bulk-action/', views.bulk_action, name='bulk_action'),
    path('wishlist/add/<int:property_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:property_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', views.wishlist_page, name='wishlist_page'),
    path('change-language/<str:language_code>/', views.change_language, name='change_language'),
    path('admin-dashboard/pending-paid-bookings/', views.pending_paid_bookings_dashboard, name='pending_paid_bookings_dashboard'),
    path('admin-dashboard/pending-paid-bookings/confirm/<int:booking_id>/', views.confirm_pending_booking_dashboard, name='confirm_pending_booking_dashboard'),
    path('booking/<int:booking_id>/', views.booking_detail, name='booking_detail'),
    path('booking/<int:booking_id>/comment/', views.add_comment, name='add_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('property/<int:property_id>/comment/', views.add_property_comment, name='add_property_comment'),
    path('property-comment/<int:comment_id>/delete/', views.delete_property_comment, name='delete_property_comment'),
]
